version: '3.5'

services:
  jenkins:
    container_name: jenkins-docker-mine
    hostname: jenkins
    image: mine/jenkins:latest
    ports:
     - '8081:8080'
     - '50001:50000'
    volumes:
     - jenkins-data:/var/jenkins_home/
     - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-data:  
  
